//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Mahjongg.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_PROGRESS                    102
#define IDR_MAINFRAME                   128
#define IDS_ERROR_CAPTION               129
#define IDI_TILESET                     129
#define IDS_VERSION_FORMAT              130
#define IDR_MJ_EXPERT                   130
#define IDI_SAVE_GAME                   130
#define IDS_ABOUT                       131
#define IDR_MAINFRAME1                  131
#define IDR_MJ_FIREWORKS                131
#define IDI_LAYOUT                      131
#define IDS_LAYOUT_FILTER               132
#define IDI_SKIN                        132
#define IDS_STATUS                      133
#define IDS_TILESET_FILTER              134
#define IDS_IMAGE_FILTER                135
#define IDS_NEW_GAME                    136
#define IDS_SAVE_GAME_FILTER            137
#define IDS_TILES_LEFT                  138
#define IDS_REGISTERED                  139
#define IDS_UNREGISTERED                140
#define IDS_GAME_TIME_DAYS              141
#define IDS_GAME_TIME_HOURS             142
#define IDS_GAME_TIME                   143
#define IDS_COL_STARTED                 144
#define IDS_COL_PLAYED                  145
#define IDS_COL_PLAYER                  146
#define IDS_KEY_ENTERED                 147
#define IDS_BEGINNER_HINT_CAPTION       148
#define IDS_TILES_NOT_EQUAL             149
#define IDS_TILE_BLOCKED                150
#define IDS_SWITCH_EXPERT_MODE          151
#define IDS_NOT_AVAILABLE               152
#define IDS_TILESET_LIST_DESCRIPTION    153
#define IDS_TILESET_LIST_AUTHOR         154
#define IDS_LAYOUT_LIST_DESCRIPTION     155
#define IDS_TILESET_DEFAULT             156
#define IDS_LAYOUT_DEFAULT              157
#define IDS_TILES_LEFT_TPL              158
#define IDS_GAME_TIME_DAYS_TPL          159
#define IDS_DEFAULT                     160
#define IDS_ERR_MONO                    161
#define IDS_ERR_16COL                   162
#define IDS_ERR_256COL                  163
#define IDS_STRING164                   164
#define IDS_ERR_NO_DRIVER               164
#define IDS_GAME_OPTIONS                165
#define IDS_VIDEO_OPTIONS               166
#define IDS_SOUND_OPTIONS               167
#define IDS_STRING168                   168
#define IDS_UNKNOWN                     168
#define IDS_SAVE_GAME_FOLDER            169
#define IDS_LAYOUTS_FOLDER              170
#define IDS_TILESET_FOLDER              171
#define IDS_BACKGROUND_FOLDER           172
#define IDS_WWW                         173
#define IDS_DISTRIBUTOR_WWW             174
#define IDS_REGISTRATION                175
#define IDS_STRING176                   176
#define IDS_MUSIC_FOLDER                176
#define ID_GAME_DEMO                    201
#define ID_PLAY_SCORES                  202
#define ID_PLAY_UNDO                    203
#define ID_PLAY_HINT                    204
#define ID_PLAY_SHUFFLE                 205
#define ID_GAME_OPTIONS                 208
#define ID_TILESET_DEFAULT              209
#define ID_TILESET_LOAD                 210
#define ID_BACKGROUND_COLOR             211
#define ID_BACKGROUND_LOAD              212
#define ID_BACKGROUND_DEFAULT           213
#define ID_GAME_NEW                     216
#define ID_GAME_REPEAT                  217
#define ID_GAME_SAVE                    219
#define ID_GAME_LOAD                    220
#define IDB_LOGO                        221
#define ID_LAYOUT_DEFAULT               223
#define ID_LAYOUT_LOAD                  224
#define IDC_SETUP_SOUND                 226
#define IDC_SHOW_HINTS                  226
#define IDC_PLAYER_NAME                 227
#define IDC_REGKEY                      227
#define IDC_ABOUT_GAME                  229
#define IDC_LOGO                        231
#define IDC_REGISTER                    232
#define ID_GAME_PLAYERNAME              235
#define IDR_GAME_OVER                   239
#define IDR_GAME_OVER_EN                239
#define IDR_BACKGROUND                  240
#define IDR_WOW                         241
#define IDR_DRAGON                      242
#define IDR_FIRE                        243
#define IDR_EXPLODE                     244
#define IDR_NOMOVES                     245
#define IDC_GRAPHICS                    245
#define IDR_REMOVE                      246
#define IDC_RADIO2                      246
#define IDR_SELECT2                     247
#define IDC_RADIO3                      247
#define IDR_SELECT                      248
#define IDC_REGISTERED                  248
#define IDD_PLAYER_NAME                 249
#define IDC_EMAIL                       249
#define IDC_WWW                         250
#define IDC_SCORES                      251
#define IDC_CLOSE                       252
#define IDC_SCORES_REPLAY               253
#define IDB_FONT                        254
#define IDC_SCORES_UPLOAD               254
#define IDC_PROGRESS                    255
#define IDD_SCORES                      255
#define IDD_NAG                         256
#define IDC_BUY_NOW                     256
#define IDD_REGISTER                    257
#define IDD_TILESETS                    258
#define IDC_PASTE                       258
#define IDD_LAYOUTS                     259
#define IDC_MESSAGE                     261
#define BOTTOM_SIDE                     263
#define LEFT_SIDE                       264
#define IDC_RB_HINTS                    264
#define IDC_TEXT_HINTS                  265
#define IDC_SMART_CURSOR                266
#define IDC_TILE                        267
#define IDC_HQ_TILE_TEX                 267
#define IDC_ROTATING                    268
#define IDC_HQ_BACKGROUND               268
#define IDC_HANDCUR                     269
#define IDC_RADIO1                      269
#define IDC_CONFIG_TYPE                 269
#define IDD_BEGINNER_HINT               270
#define IDD_SETUP_EXPERT                271
#define IDC_CHECK1                      274
#define IDC_TEXTURED_SIDES              274
#define IDC_HIDE_CLOSED                 274
#define IDC_CHECK_UPDATES               274
#define IDC_SKIN_ENABLED                274
#define IDD_SETUP_GRAPHICS              275
#define IDC_CHECK2                      275
#define IDC_SMOOTH_TILES                275
#define IDC_PROXY                       275
#define IDD_SETUP_GAME                  276
#define IDC_CHECK3                      276
#define IDC_SOLVABLE_BOARDS             276
#define IDC_INTERNET_ENABLED            276
#define IDC_COLORED_LAYERS              276
#define IDD_SETUP_SOUND                 277
#define IDB_SETUP_PAGES                 278
#define IDD_SETUP_LANGUAGES             278
#define IDD_SETUP_INTERFACE             278
#define IDC_UPDATE                      279
#define IDB_TILESET_ICON                279
#define IDD_SETUP_INTERNET              279
#define IDC_LIST1                       280
#define IDC_TILESET_LIST                280
#define IDB_SCORE_PLACE                 280
#define IDB_LAYOUT_ICON                 281
#define IDR_TILE                        282
#define IDC_SELECTOR                    283
#define IDR_TILE_SIMPLE                 283
#define IDR_TILE_LOW                    283
#define IDC_FRAME                       284
#define IDR_TILE_HIGH                   284
#define IDC_SOUND                       285
#define IDR_TILE_MEDIUM                 285
#define IDC_AUTO_SAVE                   286
#define IDB_SETUP                       286
#define IDC_HINTS                       287
#define IDB_DRAGON                      287
#define IDC_GRAPHICS_MEDIUM             288
#define IDC_GRAPHICS_HIGH               289
#define IDC_LAYOUTS                     290
#define IDC_LAYOUTS_LIST                290
#define IDC_BROWSE                      291
#define IDC_COMBO1                      292
#define IDC_LANGUAGE                    292
#define IDC_PROXY_NAME                  293
#define IDC_EDIT2                       294
#define IDC_PROXY_PORT                  294
#define IDC_PASSWORD                    294
#define IDC_SKIN                        295
#define IDC_HEADER                      296
#define IDC_LAYOUT                      297
#define IDC_TILESET                     298
#define IDC_DISTRIBUTOR_LOGO            299
#define IDC_MORE_INFO                   300
#define IDC_CREDITS                     300
#define IDC_LOGIN                       302
#define IDC_REGISTER_LINK               303
#define IDC_LABEL_LAYOUT                304
#define IDC_PROGRESS1                   305
#define IDC_UPLOAD_PROGRESS             305
#define IDR_STYLE1                      313
#define IDR_11                          317
#define IDR_LANG_DEFAULT                323
#define IDR_LANG_DEFAULT1               324
#define IDB_TILE_SMALL                  325
#define IDC_START_FIREWORKS             326
#define IDB_BITMAP1                     326
#define IDC_STOP_FIREWORKS              327
#define IDR_RT_MANIFEST1                327
#define IDR_GAME_WON                    328
#define ID_HELP_CONTENTS                329
#define IDB_BITMAP2                     329
#define ID_VIEW_ZOOMIN                  330
#define ID_VIEW_ZOOMOUT                 331
#define IDB_BITMAP3                     331
#define IDB_GAME_ICONS                  331
#define ID_VIEW_ROTATE_LEFT             332
#define ID_VIEW_ROTATE_RIGHT            333
#define ID_VIEW_ROTATE_UP               334
#define ID_VIEW_ROTATE_DOWN             335
#define ID_VIEW_DEFAULT                 336
#define ID_MODE_EXPERT                  337
#define ID_MODE_BEGINNER                338
#define ID_GAME_EXIT                    339
#define ID_GAME_NEW_SOLITAIRE           340
#define ID_GAME_NEW_FOUR_WINDS          341
#define ID_VIEW_ROTATED_OWN             342
#define ID_DEBUG_TICK                   343
#define ID_HELP_CHECK_UPDATES           344
#define ID_32810                        345
#define ID_32811                        346
#define ID_32812                        347
#define IDC_DEBUG_GAME_OVER             348
#define IDC_DEBUG_GAME_WON              349
#define ID_LANG_GERMAN                  350
#define ID_LANG_FRENCH                  351
#define ID_LANG_ENGLISH                 352
#define IDS_ACCOUNT_REGISTER            353
#define IDRL_TRADITIONAL                2000
#define TILE00                          5000
#define TILE01                          5001
#define TILE02                          5002
#define TILE03                          5003
#define TILE04                          5004
#define TILE05                          5005
#define TILE06                          5006
#define TILE07                          5007
#define TILE08                          5008
#define TILE09                          5009
#define TILE10                          5010
#define TILE11                          5011
#define TILE12                          5012
#define TILE13                          5013
#define TILE14                          5014
#define TILE15                          5015
#define TILE16                          5016
#define TILE17                          5017
#define TILE18                          5018
#define TILE19                          5019
#define TILE20                          5020
#define TILE21                          5021
#define TILE22                          5022
#define TILE23                          5023
#define TILE24                          5024
#define TILE25                          5025
#define TILE26                          5026
#define TILE27                          5027
#define TILE28                          5028
#define TILE29                          5029
#define TILE30                          5030
#define TILE31                          5031
#define TILE32                          5032
#define TILE33                          5033
#define TILE34                          5034
#define TILE35                          5035
#define TILE36                          5036
#define TILE37                          5037
#define TILE38                          5038
#define TILE39                          5039
#define TILE40                          5040
#define TILE41                          5041
#define TILE42                          5042
#define IDR_GAME_OVER1                  5043
#define IDR_GAME_OVER_DE                5043
#define ID_MENU_MENU                    32828

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        334
#define _APS_NEXT_COMMAND_VALUE         32868
#define _APS_NEXT_CONTROL_VALUE         306
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
